### ISSUE TITLE
Quand et comment utiliser strong, b, em et i :)

### ISSUE THREAD

**Issue by webmae** [lalysingh/tim-berners-lee#1]
https://github.com/lalysingh/tim-berners-lee/blob/3d7e5374141f546c66dd0e5258e735038adc76e2/index.html#L13

https://www.alsacreations.com/article/lire/552-strong-b-em-i-quelle-balise-utiliser-et-pourquoi.html

**Comment by lalysingh** [comment]
Corrigé :)
